name: spotify_sdk_ios
description: The iOS platform implementation of the spotify_sdk plugin.
version: 4.2.1
homepage: https://github.com/brim-borium/spotify_sdk
repository: https://github.com/brim-borium/spotify_sdk/tree/main/packages/spotify_sdk_ios
topics:
  - spotify
  - sdk
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.1'

dependencies:
  flutter:
    sdk: flutter
  spotify_sdk_platform_interface: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  plugin:
    implements: spotify_sdk
    platforms:
      ios:
        pluginClass: SpotifySdkPlugin
