name: spotify_sdk_android
description: Android implementation of spotify_sdk.
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  spotify_sdk_platform_interface:
    path: ../spotify_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  plugin:
    implements: spotify_sdk
    platforms:
      android:
        package: de.minimalme.spotify_sdk
        pluginClass: SpotifySdkPlugin
