name: spotify_sdk_android
description: The Android platform implementation of the spotify_sdk plugin.
version: 4.0.0
homepage: https://github.com/brim-borium/spotify_sdk
repository: https://github.com/brim-borium/spotify_sdk/tree/main/packages/spotify_sdk_android
topics:
  - spotify
  - sdk
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  spotify_sdk_platform_interface: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  plugin:
    implements: spotify_sdk
    platforms:
      android:
        package: de.minimalme.spotify_sdk
        pluginClass: SpotifySdkPlugin
