name: Publish to pub.dev
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # tag-pattern on pub.dev: ''

jobs:
  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: '.fvmrc'
          cache: true

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub global activate pana
          sudo apt-get install webp

      - name: Verify Pub Score
        run: |
          cd packages/spotify_sdk
          ../../.github/scripts/verify_pub_score.sh 140

  publish:
    needs: pana
    environment: 'pub.dev'
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: '.fvmrc'
          cache: true
      - name: Bootstrap Workspace
        run: |
          flutter pub get
          flutter pub global activate melos
          melos bootstrap
      - name: 🪪 Get Id Token
        uses: actions/github-script@v7
        with:
          script: |
            let pub_token = await core.getIDToken('https://pub.dev')
            core.exportVariable('PUB_TOKEN', pub_token)
      - name: 📢 Authenticate pub.dev
        run: flutter pub pub token add https://pub.dev --env-var PUB_TOKEN
      - name: 📢 Publish packages via Melos
        run: melos publish --no-dry-run --yes
